export const actionTypes = {
    LOADING: "LOADING",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILED: "LOGIN_FAILED",

    LOGUT_SUCCESS: "LOGUT_SUCCESS",
    LOGUT_FAILED: "LOGUT_FAILED",

    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAILED: "SIGNUP_FAILED",
    LOADING_STOP: "LOADING_STOP",

    MOVIE_LIST_LOADING: "MOVIE_LIST_LOADING",
    MOVIE_LIST_SUCCESS: "MOVIE_LIST_SUCCESS",
    MOVIE_LIST_FAILED: "MOVIE_LIST_FAILED",
    MOVIE_LIST_FAV: "MOVIE_LIST_FAV",
    
    RESET: "RESET",
}